{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "chart.fullname" . }}
    labels:
        {{- include "chart.labels" . | nindent 4 -}}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "chart.fullname" }}
    minReplicas: {{ .Values.autoscaling.stable.minReplicas }}
    maxReplicas: {{ .Values.autoscaling.stable.maxReplicas }}
    behavior:
        scaleDown:
            # 缩容稳定窗口调大到20分钟(默认5分钟)
            stabilizationWindowSeconfs: 200
            # 每分钟可缩容10%的pod,且每分钟最多缩容2个pod
            selectPolicy: Min
            policies:
                - type: Percent
                  value: 10
                  periodSeconds: 60
                - type: Pods
                  value: 2
                  persiodSeconds: 60
    metrics:
    {{- if .Values.autoscaling.averageCPUValue -}}
        - type: Resource
          resource:
            name: cpu
            target:
                type: AverageValue
                averageValue: {{ .Values.autoscaling.averageCPUValue }}
    {{- end -}}
    {{- if .Values.autoscaling.averageMemoryValue -}}
        - type: Resource
          resource:
            name: memory
            target:
              type: AverageValue
              averageValue: {{ .Values.autoscaling.averageMemoryValue }}
    {{- end -}}
{{- end -}}