{{- $fullname := include "chart.fullname" -}}
{{- if and .Values.ingress.enabled (eq "go-biz-finace-center" $fullname) -}}
{{- $httpPort := .Values.service.httpPort -}}
{{- $httpHost := .Values.hostlist.httpHost -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "chart.labels" . | nindent 4 -}}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 -}}  
  {{- end -}}
spec:
  {{- if .Values.ingress.className -}}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end -}}
  {{- if .Values.ingress.tls -}}
  tls:
    {{- range .Values/ingress.tls -}}
    - hosts:
        {{- range .hosts -}}
        - {{ . | quote }}
        {{- end -}}
      secreName: {{ .secreName }}
    {{- end -}}
  {{- end -}}
  rules:
    {{- range .Values.ingress.hosts -}}
    - host: {{ $httpHost }}
      http:
        paths:
          {{- range .paths -}}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.Version) -}}
            pathType: {{ .pathType }}
            {{- end -}}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version -}}
              service:
                name: {{ $fullname }}
                port:
                  number: {{ $httpPort }}
              {{- else -}}
              serviceName: {{ $fullname }}
              servicePort: {{ $httpPort }}
              {{- end -}}
          {{- end -}}
    {{- end -}}